name = "testerr"
main = "_worker.js"
compatibility_date = "2023-05-26"
# node_compat = true
workers_dev = true

[[routers]]
pattern = "iseee.us.kg"
custom_domain = true

[vars]
PROXYIP = "206.237.98.76:587"
UUID = "323dad2b-a854-4298-883f-88ab2dd9d964"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
